name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: hugoh/spoon-tools/.github/workflows/spoon-hk.yml@c88e2a782be5da2eb883d94c32450dec117c5493
