name: Release

permissions:
  contents: write
  pages: write
  id-token: write

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: hugoh/spoon-tools/.github/workflows/spoon-release.yml@c88e2a782be5da2eb883d94c32450dec117c5493
    with:
      spoon_name: MacWatcher
