name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    name: Lua ${{ matrix.lua }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua: [ "5.4" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua }}

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Run tests
        run: make test
