name: Tests

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  test:
    uses: hugoh/spoon-tools/.github/workflows/spoon-tests.yml@c88e2a782be5da2eb883d94c32450dec117c5493
